### ISSUE TITLE
Unable to resolve module `./util` from `node_modules\react-native-ytdl\lib\index.js`:

### ISSUE THREAD

**Issue by dungle27** [ytdl-js/react-native-ytdl#51]
Hello
I try install latest version: 4.0.4
but occur this error: 
Unable to resolve module `./util` from `node_modules\react-native-ytdl\lib\index.js`:

please resolve help me
thank you so much!!

**Comment by AbelTesfaye** [comment]
Duplicate of https://github.com/ytdl-js/react-native-ytdl/issues/47

**Comment by dungle27** [comment]
@AbelTesfaye 
thank you!!!
