### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Kyewn** [ytdl-js/react-native-ytdl#52]
I am new and experimenting with using this module, but my request returned me this error:

`Access to fetch at 'https://www.youtube.com/watch?v=5a1G-GlDi2s&hl=en&bpctr=1606293386&pbj=1' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque [response](url) serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Based on my understanding of request headers, it should be the header that should be included with the request right? Is this a problem of the header content or is it just my client-side problem?

**Comment by benkaiser** [comment]
@Kyewn this library can only be run in contexts where you can make requests to youtube with custom headers. Unfortuantely there is no way to do this in regular javascript.
This library is intended for use in React Native (i.e. on a mobile device).
If you want to run this library from a browser, the only way I have found how is to write a chrome extension and have this library code run from within the background context of the extension.

**Comment by Kyewn** [comment]
@benkaiser yes, I know it is intended for React native usage, I was using it to create a React app after all. But for some reason, it just returns this error to me whenever I try to send out a request using `await ytdl()`. (the context here is that there are multiple buttons that correspond to different videos, at max 10 of them, and when clicked, it should call out a function to fetch the downloadable links).

Everything else works fine, and I figure it's just that line of code that's causing problems.

**Comment by benkaiser** [comment]
@Kyewn what context are you running the library from? If it's a browser / website then you're not going to have any luck getting around the cross origin warnings.

**Comment by Kyewn** [comment]
Yeap it's a browser/website :v So, I see I can't do anything to change that. does this library work only when used to download the videos in the command line?

**Comment by benkaiser** [comment]
@Kyewn it works in [React Native](https://reactnative.dev/), i.e. on a mobile device and not on the web

**Comment by Kyewn** [comment]
Alright, gotcha. Thanks for clarifying.
