### ISSUE TITLE
library does not work anymore

### ISSUE THREAD

**Issue by batuhansahan** [ytdl-js/react-native-ytdl#54]
is it deprecated

**Comment by AbelTesfaye** [comment]
Fixed on latest update

**Comment by batuhansahan** [comment]
i think its still not working did you test it.

**Comment by AbelTesfaye** [comment]
I did test it...you're probably experiencing cache issues. https://github.com/ytdl-js/react-native-ytdl/issues/47#issuecomment-720129063

**Comment by batuhansahan** [comment]
@AbelTesfaye thank you for your hardwork.
