### ISSUE TITLE
Process env checking fails in certain contexts

### ISSUE THREAD

**Issue by benkaiser** [ytdl-js/react-native-ytdl#56]
The last rebase brought in some update checking logic, which uses an env variable `process.env.YTDL_NO_UPDATE`.

Since I'm consuming this from a background chrome extension script it's failing on that line.
Can we consider keeping this line different from ytdl-core? it probably doesn't make sense including the update check anyway.

**Comment by AbelTesfaye** [comment]
Removing update checks might be a bad way to go, I expect devs (while debugging) might want to know when new releases are available for use.

I have absolutely no experience with chrome extensions but, if you are experiencing a declaration error, could it be possible to fix it by importing this library **after** declaring the variable? 

Something like:

```javascript
window.process = { env: { YTDL_NO_UPDATE: true } };
import ytdl from "react-native-ytdl"

const youtubeURL = 'http://www.youtube.com/watch?v=04GiqLjRO3A';
const urls = await ytdl(youtubeURL, { quality: 'highestaudio' });
console.log(urls)

```

**Comment by benkaiser** [comment]
@AbelTesfaye good point, I've taken your advice and gone a similar route. My extension is built using webpack, so I used a built-in webpack plugin to mock out process.env. Here is the commit for future reference in case anyone also encounters the same problem:

https://github.com/benkaiser/Stretto-Helper-Extension/commit/0d25a0d14531c75b71f55d4fea93abf2b9846f06
