### ISSUE TITLE
Can't get relate video in latest version.

### ISSUE THREAD

**Issue by dungle27** [ytdl-js/react-native-ytdl#59]
Hello, 
I'm using latest version:   "react-native-ytdl": "^4.1.2",
when I use: 
            let info = await ytdl.getInfo(id_video);
=> can't get related_videos value in info

old version still get related_videos value normal

Please help check this issue!!!

**Comment by ngocluan1192** [comment]
I have same issue :(

**Comment by dungle27** [comment]
@AbelTesfaye 
Could you check this issue help us?

**Comment by ngocluan1192** [comment]
@AbelTesfaye FYI, I think it has been resolved.
https://github.com/fent/node-ytdl-core/issues/800

**Comment by AbelTesfaye** [comment]
Should be fixed now. 

Btw, cloning this library and running `npm run clone-and-patch` will try to get the latest node-ytdl-core and will patch it to make it compatible with react-native. (wont work 100% of the time, but it's worth a shot)

**Comment by ngocluan1192** [comment]
> Should be fixed now.
> 
> Btw, cloning this library and running `npm run clone-and-patch` will try to get the latest node-ytdl-core and will patch it to make it compatible with react-native. (wont work 100% of the time, but it's worth a shot)

Thanks for your hard work!!!

**Comment by dungle27** [comment]
fixed in latest version
thanks @AbelTesfaye
