### ISSUE TITLE
This package not support with IOS anymore???

### ISSUE THREAD

**Issue by tyhour** [ytdl-js/react-native-ytdl#74]
For android it really work fine, but IOS not working with ytdl package I don't know why. Maybe this package not update anymore.
if have any solution please let me know. (IOS 14.*)

**Comment by TylerOlthuizen** [comment]
Yeah I'm having a similar issue. I don't know if this uses ytdl-core but there was an update to that about 7 days ago. I too can say it works on Android devices and simulators but not on IOS devices or Simulators. However this was working even a week ago or more.

**Comment by tyhour** [comment]
> Yeah I'm having a similar issue. I don't know if this uses ytdl-core but there was an update to that about 7 days ago. I too can say it works on Android devices and simulators but not on IOS devices or Simulators. However this was working even a week ago or more.

Now I used ytdl-core with rest api for my app right now. I thinks this package not update anymore. So issue has been fixed for me.
